/**
 * Copyright (C) 2005, 2009  Kerri Morgan
 *
 * This file is part of the planar program package.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * **/

#include "runTests.h"
#include "K2_Alg.h"
#include "removeVertexAlg.h"
#include "addVertexAlg.h"
#include "genRandGraph.h"
#include "hybridAlg.h"
#include "graphGen.h"
#include "bollobas.h"
#include <time.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_LEN 50

/******************************************************************************
** Function:	runTestA
** Description:	Functions runs approximation algorithms on the graph and records
**		the time taken and performance
**		Graph is maximum degree d and is generated by Morgan algorithm
** Inputs:	size - number of vertices in graph
** Return Value:none
** Side Effects:Outputs information to screen
** Created:	Kerri Morgan	20th April, 2005
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTestA( int size, int d)
{
	struct timeval startV, finishV;
	double start, finish;
	double elapsed;
	int P;
	Vertex* G=NULL;
	int i;
	FILE * infile=NULL;
	char filename[20];
	char temp[10];	
	double A_worstTime=0;
	double B_worstTime=0;
	double C_worstTime=0;
	double A_totalTime=0;
	double B_totalTime=0;
	double C_totalTime=0;

	
	strcpy(filename, "TEST");
	sprintf(temp, "%d", size);
	strcat(filename, temp);
	strcat(filename, "_");
	sprintf(temp, "%d", d);
	strcat(filename, temp);

	infile= fopen(filename, "w");
	if(infile ==NULL)
	{
		fprintf(stderr, "ERROR 7.3: Unable to open %s\n", filename);
		exit(1);
	}
	/* testing */
	
	fprintf(infile, "TEST: size is %d and degree is %d\n", size, d);
	for(i=0; i<NUMTESTS; i++)
	{
		/* create a graph of given size*/
		G=genGraph3(size, d);
		if(G==NULL)
		{
			fprintf(stderr, "ERROR 7.1: Unable to create random graph using the Morgan method\n");
			exit(1);
		}
		initMembers(G, size);
		gettimeofday(&startV, NULL);	
		start = clock();
		P=removeVertAlg(G, size, 0);
		finish = clock();
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
		elapsed = finish - start;
		
		fprintf(infile, "TIME: %.8f microseconds ", elapsed);
		fprintf(infile, "SIZE: %d ", P);
		fprintf(infile, "PERCENTAGE RETAINED %.8f\n", (float)P/size);

		if(A_worstTime < elapsed)
		{
			A_worstTime=elapsed;
		}
		A_totalTime+=elapsed;

		initMembers(G, size);
		gettimeofday(&startV, NULL);	
		P=addVertAlg(G, size, 0);
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
		elapsed = finish - start;
		
		fprintf(infile, "TIME: %.8f microseconds ", elapsed);
		fprintf(infile, "SIZE: %d ", P);
		fprintf(infile, "PERCENTAGE RETAINED %.8f\n", (float)P/size);
		
		if(B_worstTime < elapsed)
		{
			B_worstTime=elapsed;
		}
		B_totalTime+=elapsed;
		
		initMembers(G, size);
		gettimeofday(&startV, NULL);	
		P=hybrid(G, size, 0);
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
		elapsed = finish - start;
		
		fprintf(infile, "TIME: %.8f microseconds ", elapsed);
		fprintf(infile, "SIZE: %d ", P);
		fprintf(infile, "PERCENTAGE RETAINED %.8f\n", (float)P/size);

		if(C_worstTime < elapsed)
		{
			C_worstTime=elapsed;
		}
		C_totalTime+=elapsed;
		
		killGraph(G, size);
		G=NULL;
	}
	fprintf(infile, "%.8f %.8f %.8f %.8f\n", A_worstTime, A_totalTime, B_worstTime, B_totalTime);
	fclose(infile);
}
/******************************************************************************
** Function:	runTestB
** Description:	Functions runs approximation algorithms on the graph and records
**		the time taken and performance
**		Graph is maximum degree d and is generated by Steger-Wormald
**		algorithm
** Inputs:	size - number of vertices in graph
** Return Value:none
** Side Effects:Outputs information to screen
** Created:	Kerri Morgan	20th April, 2005
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTestB( int size, int d)
{
	struct timeval startV, finishV;
	double start, finish;
	double elapsed;
	int P;
	Vertex* G=NULL;
	int i;

	double A_worstTime=0;
	double B_worstTime=0;
	double A_totalTime=0;
	double B_totalTime=0;
	
	for(i=0; i<NUMTESTS; i++)
	{
		/* create a graph of given size*/
		G=genGraph(size, d);
		if(G==NULL)
		{
			fprintf(stderr, "ERROR 7.2: Unable to create random graph using the Steger-Wormald method\n");
			exit(1);
		}
		initMembers(G, size);
		
		gettimeofday(&startV, NULL);	
		P=removeVertAlg(G, size, 0);
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
		elapsed = finish - start;
	
		printf("Vertex Addition Algorithm\n");
		printf("TIME: %.8f microseconds ", elapsed);
		printf("SIZE: %d ", P);
		printf("PERCENTAGE RETAINED %.8f\n", (float)P/size);

		if(A_worstTime < elapsed)
		{
			A_worstTime=elapsed;
		}
		A_totalTime+=elapsed;

		initMembers(G, size);
		gettimeofday(&startV, NULL);	
		P=addVertAlg(G, size, 0);
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
		elapsed = finish - start;
	
		printf("VERTEX REMOVAL ALGORITHM\n");
		printf("TIME: %.8f seconds ", elapsed);
		printf("SIZE: %d ", P);
		printf("PERCENTAGE RETAINED %.8f\n", (float)P/size);
		
		if(B_worstTime < elapsed)
		{
			B_worstTime=elapsed;
		}
		B_totalTime+=elapsed;

		killGraph(G, size);
		G=NULL;
	}
	printf("%.8f %.8f %.8f %.8f\n", A_worstTime, A_totalTime, B_worstTime, B_totalTime);
}
/******************************************************************************
** Function:	runTests
** Description:	Function co-ordinates the running of all tests
** Inputs:	none
** Return Value:none
** Side Effects:Information is output to screen
** Created:	Kerri Morgan	27th April, 2005
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTests(void)
{
	int i, j, k;
	int degree[7] = { 3, 4, 5, 6, 7, 8, 9};
	int size [23] = {20,40,60,80,100,200,300,400,500,600,700,800,900, 1000,2000,3000,4000,5000,6000,7000,8000,9000, 10000};
	char filename[100];
	char temp[10];
	int numTests;

	/* for each degree */
	for(j=1; j<2; j++)
	//for(j=5; j<7; j++)
	//for(j=0; j<7; j++)
	{
		/* for each size */
		//for(i=0; i<23; i++)
		for(i=0; i<23; i++)
		{
			if(size[i] > 1000)
			{
				numTests = 20;
			}
			else
			{
				numTests =50;
			}
			/* for each graph generation method */
		//	for(k=0; k<3; k++)
			for(k=0; k<3; k++)
			{

				printf("TEST::  Degree %d, size %d, method %d\n", degree[j], size[i], k);
				strcpy(filename, "/home/kerri/PROJECT/TESTS/n");
				sprintf(temp, "%d", size[i]);
				strcat(filename, temp);
				strcat(filename, "d");
				sprintf(temp,  "%d", degree[j]);
				strcat(filename, temp);
				if(k==0) /* Bollobas */
				{
					if(size[i] <100 && degree[j]< 7)
					{
						strcat(filename, "/B");
		
						runTest_OP_2006( filename, size[i], degree[j], numTests, "B");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "B");
						//runTest_M_MIPS(filename, size[i], degree[j], numTests, "B");
						//runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "B");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "B");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "B");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "B");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "B");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "B");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "B");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "B");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "B");
					}
					else if(size[i]<300 && degree[j] < 6)
					{
						strcat(filename, "/B");
						runTest_OP_2006( filename, size[i], degree[j], numTests, "B");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS(filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "B");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "B");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "B");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "B");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "B");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "B");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "B");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "B");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "B");
						
					}
					else if (size[i]<1000 && degree[j] <5)
					{
						strcat(filename, "/B");
						runTest_OP_2006( filename, size[i], degree[j], numTests, "B");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS(filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "B");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "B");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "B");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "B");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "B");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "B");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "B");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "B");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "B");
					}
					else if(size[i]==1000 && degree[j]==3)
					{
						strcat(filename, "/B");
						runTest_OP_2006( filename, size[i], degree[j], numTests, "B");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS(filename, size[i], degree[j], numTests, "B");
					//	runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "B");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "B");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "B");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "B");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "B");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "B");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "B");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "B");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "B");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "B");
					}
					/* else do nothing */

				}
				else if(k==1) /* StegerWormald */
				{
						strcat(filename, "/SW");
						runTest_OP_2006( filename, size[i], degree[j], numTests, "SW");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "SW");
					//	runTest_M_MIPS(filename, size[i], degree[j], numTests, "SW");
					//	runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "SW");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "SW");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "SW");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "SW");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "SW");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "SW");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "SW");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "SW");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "SW");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "SW");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "SW");
				}
				else /* k==2  Erdos*/
				{
						strcat(filename, "/E");
						runTest_OP_2006( filename, size[i], degree[j], numTests, "E");
						//runTest_palmTree_2006( filename, size[i], degree[j], numTests, "E");
					//	runTest_M_MIPS(filename, size[i], degree[j], numTests, "E");
					//	runTest_M_MIPS_III(filename, size[i], degree[j], numTests, "E");
					//	runTest_Mixture(filename, size[i], degree[j], numTests, "E");
					//	runTest_Subset(filename, size[i], degree[j], numTests, "E");
					//	runTest_removalAlg(filename, size[i], degree[j], numTests, "E");
					//	runTest_additionAlg(filename, size[i], degree[j], numTests, "E");
					//	runTest_palmTree(filename, size[i], degree[j], numTests, "E");
					//	runTest_Outerplanar(filename, size[i], degree[j], numTests, "E");	
					//	runTest_Trees(filename, size[i], degree[j], numTests, "E");
					//	runTest_IndependentSet(filename, size[i], degree[j], numTests, "E");
					//	runTest_H_L(filename, size[i], degree[j], numTests, "E");
					//	runTest_Hybrid(filename, size[i], degree[j], numTests, "E");
				}

			
			}
		}
	}
}
/******************************************************************************
** Function:	createTestGraphs
** Description:	Function creates n test graphs using the selected method.
** Inputs:	size - number of vertices
**		degree - the maximum (or average if using Erdos' method)
**		degree of graph
**		method - 1=Bollobas, 2= Steger-Wormald, 3=Erdos
** Return Value:none
** Side Effects:creates files containing graphs
** Created:	Kerri Morgan	27th June, 2005
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void createTestGraphs(int size, int degree, int method)
{
	int i,j,k;
	char temp[MAX_LEN];
	char filename[MAX_LEN];
	FILE* outfile=NULL;
	int num;
	Vertex* G=NULL;

	printf("Enter number of test files to create\n");
	fgets(temp, MAX_LEN,stdin); 
	while(sscanf(temp, "%d", &num)!=1)
	{
		printf("Incorrect input - Enter number of test files to create\n");
		fgets(temp, MAX_LEN,stdin); 
	}
	for(i=0; i<num; i++)
	{
		strcpy(filename, "TEST");
		sprintf(temp, "%d", i);
		strcat(filename, "_");
		strcat(filename, temp);
		outfile=fopen(filename, "w");
printf("TEST file name is %s\n", filename);
		if(outfile == NULL)
		{
			fprintf(stderr, "ERROR 7.4: Unable to open file %s\n", filename);
			exit(1);
		}
		if(G!=NULL)
		{
			killGraph(G, size);
			G=NULL;
		}
		if(method == 1)	/* Bollobas Method */
		{
			G = createB_graph(size, degree);
			//G=createRandomGraph(size, degree);
		}
		else if(method ==2)
		{
			G = genGraph3(size, degree);
		}
		else if(method ==3)
		{
			G=classicalGen(size, degree);
		}
		if(G!=NULL)
		{
			fprintf(outfile, "%d\n", size);
			fprintf(outfile, "%d\n", (size*degree)/2);
	
			for(k=0; k<size; k++)
			{
				fprintf(outfile, "%d", G[k].degree);
				for(j=0; j<G[k].degree; j++)
				{
					fprintf(outfile, " %d", G[k].adjVerts[j]);
				}
				fprintf(outfile, "\n");
			}
		}
		else
		{
			fprintf(stderr, "ERROR 7.5: Failure to save to file %s\n", filename);
			exit(1);
		}
		fclose(outfile);
	}
	if(G!=NULL)
	{
		killGraph(G, size);
	}
}

/******************************************************************************
** Function:	runTest_removeAlg
** Description: Function runs tests on the vertex removal algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	4th August, 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_removalAlg(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/RemoveAlg");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Vertex Removal Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=removeVertAlg(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}


/******************************************************************************
** Function:	runTest_additionAlg
** Description: Function runs tests on the vertex additon algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_additionAlg(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	//strcpy(filename2, "TEST_RESULTS/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/AdditionAlg");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Vertex Addition Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=addVertAlg(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}
/******************************************************************************
** Function:	runTest_OP_2006
** Description: Function runs tests on the OP algorithm1
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_OP_2006(char* filename, int n, int d, int num, char* method)
{
	struct timeval startV, finishV;
	double start, finish;
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	//clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS/");
	//strcpy(filename2, "TEST_RESULTS/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	//strcat(filename2, "/OuterPlanar_NONPT_Alg1_2006");
	//strcat(filename2, "/PALM_TREE_3");
	strcat(filename2, "/M_MIPS_III");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is M_MIPS Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
	//	fprintf(stderr, "Test %d on size %d and degree %d with method %s\n\n", i, d,n, method);
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
	//	start = clock();	
		
		gettimeofday(&startV, NULL);	

		
//		P=CreateOPGraph(G, n, 0);
	//	P=M_MIPS_II(G,n, 0);		
//		P=M_MIPS(G,n, 0);		
		P=M_MIPS_III(G,n, 0);		
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
	
		elapsed = finish -start;	
	//	finish=clock();
	//	elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
	//	elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}



/******************************************************************************
** Function:	runTest_palmTree_2006
** Description: Function runs tests on the palm tree algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	This is not really a palm tree - it is OP alg that grew from 
**		palm trees and bares little resemblance.
** Acknowledgements:
******************************************************************************/
void runTest_palmTree_2006(char* filename, int n, int d, int num, char* method)
{
	struct timeval startV, finishV;
	double start, finish;
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	//clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS/");
	//strcpy(filename2, "TEST_RESULTS/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/OuterPlanar2006");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Palm Tree Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
	//	fprintf(stderr, "Test %d on size %d and degree %d with method %s\n\n", i, d,n, method);
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
	//	start = clock();	
		
		gettimeofday(&startV, NULL);	

		
		P=PT_2006(G, n, 0);
		
		gettimeofday(&finishV, NULL);	
		start =(double)startV.tv_sec * 1000000 + startV.tv_usec;
		finish =(double)finishV.tv_sec * 1000000 + finishV.tv_usec;
	
		elapsed = finish -start;	
	//	finish=clock();
	//	elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
	//	elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}


/******************************************************************************
** Function:	runTest_palmTree
** Description: Function runs tests on the palm tree algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_palmTree(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	//strcpy(filename2, "TEST_RESULTS/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/PalmTree");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Palm Tree Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=M_MIPS_II(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}


/******************************************************************************
** Function:	runTest_H_L
** Description: Function runs tests on the H&L algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_H_L(char* filename, int n, int d, int num, char* method)
{

	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	//strcpy(filename2, "TEST_RESULTS/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/H&L");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is H&L Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=H_L_alg(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_Trees
** Description: Function runs tests on the GrowCleverTrees algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_Trees(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/CleverTree");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Vertex Removal Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=GrowCleverTrees(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_Subset
** Description: Function runs tests on the GrowCleverTrees algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_Subset(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/Subset");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Subset Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=subsetRemove(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}
		

/******************************************************************************
** Function:	runTest_Hybrid
** Description: Function runs tests on the Hybrid algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_Hybrid(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/HYBRID");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Hybrid Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=hybrid(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_M_MIPS
** Description: Function runs tests on the GrowCleverTrees algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_M_MIPS(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/M_MIPS");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is M_MIPS \n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=M_MIPS(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_Mixed
** Description: Function runs tests on an algorithm combining the Subset removal
**		algorithm and the extendGraph algorithm
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:Subset Removal Algorithm is based on ideas of Keith Edwards
******************************************************************************/
void runTest_mixture(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/Mixed");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Subset Removal and extended by the extend graph algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=mixture_Alg(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_IndependentSet
** Description: Function runs tests on an algorithm producing an independent
**		set
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	5 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_IndependentSet(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/IndependentSet");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Independent Set\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=growCleverSingleTreeAlg(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_Outerplanar
** Description: Function runs tests on an algorithm producing an outerplanar
**		subgraph of G. 
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	24 September , 2005	
** Modified:
** Comments:	NOTE:  This graph is not maximally outerplanar
** Acknowledgements:
******************************************************************************/
void runTest_Outerplanar(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/Outerplanar");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is Outerplanar Set\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=CreateOPGraph(G, n, 0);
		
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_M_MIPSIII
** Description: Function runs tests on an algorithm producing a palm tree
** 		extended by the extendGraph function
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	24 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:
******************************************************************************/
void runTest_M_MIPS_III(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/M_MIPS_III");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is  M_MIPS_III\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=M_MIPS_III(G, n, 0);
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed = elapsed * 1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}

/******************************************************************************
** Function:	runTest_Mixture
** Description: Function runs tests on an algorithm that combines subset
**		removal algorithm with extendGraph algorithm
** 		extended by the extendGraph function
** Inputs:	filename - directory containing set of files.
**		Each file contains a graph to be used in tests
**		n - number of vertices in each graph
**		d - the degree of the graph 
**		(in the case of graphs generated by the Steger-Wormald method
**		and Bollobas method this is the maximum degree of the graph.  
**		In the case of graphs generated by the Erdos method, this is
**		average degree).
**		num - number of graphs in file
**		method - string indicating method used to generate the graphs
** Return Value:none
** Side Effects:Creates a file TESTRESULTS/n_d/method which contains the results
** Created:	Kerri Morgan	25 September , 2005	
** Modified:
** Comments:	
** Acknowledgements:Subset Removal Algorithm is based on ideas of Keith Edwards
******************************************************************************/
void runTest_Mixture(char* filename, int n, int d, int num, char* method)
{
	FILE* outfile = NULL;
	int i;
	int P=0;
	Vertex* G=NULL;
	char filename1[50];
	char filename2[50];
	char filename3[50];
	char temp[10];	
	double avgTime=0;
	double avgSize=0;
	int sizes[50];
	clock_t start, finish;
	double elapsed;
	double times[50];
	
	double sum1=0.0;
	double sum2=0.0;


	strcpy(filename2, "TEST_RESULTS2/");
	sprintf(temp, "%d", n);
	strcat(filename2, temp);
	strcat(filename2, "_");
	sprintf(temp, "%d", d);
	strcat(filename2, temp);
	strcat(filename2, "/");
	strcat(filename2, method);	/* graph generation */
	strcat(filename2, "/Mixture");
	
	outfile= fopen(filename2, "w");
	if(outfile ==NULL)
	{
		fprintf(stderr, "ERROR 7.6: Unable to open %s\n", filename2);
		exit(1);
	}

	strcpy(filename1, filename);
	strcat(filename1, "/");
	strcat(filename1, "TEST_");
	//printf("TEST: size is %d and degree is %d and method \n", n, d);
	fprintf(outfile, "TEST: size is %d and degree is %d\n", n, d);
	fprintf(outfile,  "Algorithm is  Mixture Algorithm\n\n");
	fprintf(outfile, "TIME(Microseconds):PERCENTAGE RETAINED:	SIZE OF P:\n"); 

	/* for each test graph*/
	for(i=0; i<num; i++)
	{
		strcpy(filename3, filename1); /* filename/TEST_*/
		sprintf(temp, "%d", i);
		strcat(filename3, temp);
		G = readGraphFromFile(filename3, n, d);
		initMembers(G, n);

		initAdjLists(G, n);
		start =0;
		finish=0;	
		start = clock();	
		P=mixture_Alg(G, n, 0);
		finish=clock();
		elapsed = (double)(finish - start)/CLOCKS_PER_SEC;
		elapsed*=1000000;
		sizes[i]=P;
		times[i]=elapsed;
		avgTime+=elapsed;
		avgSize+=(double)P;


//		printf("Elapsed %.2f microsecs\n", elapsed);
//		printf("CPU %f microseconds\n", difftime/(double)MILLION);
		fprintf(outfile, "%.2f \t\t", elapsed);
		fprintf(outfile, "%.8f\t", (float)P*100.0/n);
		fprintf(outfile, "%d\n", P);

		killGraph(G, n);

	}

	/* get mean and standard deviation */
	avgTime=avgTime/num;
	fprintf(outfile, "Mean Time: %.2f microseconds\n", avgTime);
	avgSize = avgSize/num;
	fprintf(outfile, "Mean Size: %.2f\n", avgSize);
	for(i=0; i<num; i++)
	{
		sum1+=pow(times[i]-avgTime, 2);
		sum2+=pow(sizes[i]-avgSize, 2);
	}
		
	fprintf(outfile, "Std.Dev. Time: %.2f microseconds\n", sqrt(sum1/(num-1)));
	fprintf(outfile, "Std.Dev. Size: %.2f\n", sqrt(sum2/(num-1)));
	printf("%.2f (%.2f)\t%.2f (%.2f)\n", avgSize, sqrt(sum2/(num-1)), avgTime, sqrt(sum1/(num-1)));
	fclose(outfile);
}


